# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '1.15.2.dev14+g3ad8635.d20220104'
version_tuple = (1, 15, 2, 'dev14', 'g3ad8635.d20220104')
